/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhookRouteImport } from './routes/webhook'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as TestTriggerRouteImport } from './routes/test/trigger'
import { Route as TestStripeCheckoutRouteImport } from './routes/test/stripe-checkout'
import { Route as TestSmokeRouteImport } from './routes/test/smoke'
import { Route as AssetsSplatRouteImport } from './routes/assets/$'
import { Route as ApiReferenceRouteImport } from './routes/api/reference'
import { Route as ApiOpenapiDotjsonRouteImport } from './routes/api/openapi[.]json'
import { Route as ShellOperatorRouteImport } from './routes/_shell/operator'
import { Route as ShellCliLoginRouteImport } from './routes/_shell/cli-login'
import { Route as ApiV1CliAuthorizationsRouteImport } from './routes/api/v1/cli-authorizations'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiDaemonsEnrollRouteImport } from './routes/api/daemons/enroll'
import { Route as ApiDaemonsDaemonIdRouteImport } from './routes/api/daemons/$daemonId'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing/webhook'
import { Route as ApiBillingPlansRouteImport } from './routes/api/billing/plans'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AgentExecutionsExecutionIdMcpRouteImport } from './routes/agent-executions/$executionId/mcp'
import { Route as ApiV1CliAuthorizationsPollRouteImport } from './routes/api/v1/cli-authorizations/poll'
import { Route as ApiIntegrationsSlackEventsRouteImport } from './routes/api/integrations/slack/events'
import { Route as ApiIntegrationsSlackCallbackRouteImport } from './routes/api/integrations/slack/callback'
import { Route as ApiIntegrationsLinearEventsRouteImport } from './routes/api/integrations/linear/events'
import { Route as ApiIntegrationsLinearCallbackRouteImport } from './routes/api/integrations/linear/callback'
import { Route as ApiIntegrationsGithubSetupRouteImport } from './routes/api/integrations/github/setup'
import { Route as ApiIntegrationsGithubCallbackRouteImport } from './routes/api/integrations/github/callback'
import { Route as ApiIntegrationsDiscordCallbackRouteImport } from './routes/api/integrations/discord/callback'
import { Route as AgentExecutionsExecutionIdAttachmentsAttachmentIdRouteImport } from './routes/agent-executions/$executionId/attachments/$attachmentId'
import { Route as ShellOOrganizationSlugUsageRouteImport } from './routes/_shell/o/$organizationSlug/usage'
import { Route as ShellOOrganizationSlugTeamRouteImport } from './routes/_shell/o/$organizationSlug/team'
import { Route as ShellOOrganizationSlugProjectsRouteImport } from './routes/_shell/o/$organizationSlug/projects'
import { Route as ShellOOrganizationSlugDaemonsRouteImport } from './routes/_shell/o/$organizationSlug/daemons'
import { Route as ShellOOrganizationSlugConnectionsRouteImport } from './routes/_shell/o/$organizationSlug/connections'
import { Route as ShellOOrganizationSlugBillingRouteImport } from './routes/_shell/o/$organizationSlug/billing'
import { Route as ShellOOrganizationSlugApiKeysRouteImport } from './routes/_shell/o/$organizationSlug/api-keys'
import { Route as ShellOOrganizationSlugProjectsIndexRouteImport } from './routes/_shell/o/$organizationSlug/projects/index'
import { Route as ShellOOrganizationSlugProjectsProjectSlugOverviewRouteImport } from './routes/_shell/o/$organizationSlug/projects/$projectSlug/overview'
import { Route as ShellOOrganizationSlugProjectsProjectSlugConfigurationRouteImport } from './routes/_shell/o/$organizationSlug/projects/$projectSlug/configuration'
import { Route as ShellOOrganizationSlugProjectsProjectSlugActivityRouteImport } from './routes/_shell/o/$organizationSlug/projects/$projectSlug/activity'
import { Route as ShellOOrganizationSlugProjectsProjectSlugActivityIndexRouteImport } from './routes/_shell/o/$organizationSlug/projects/$projectSlug/activity/index'
import { Route as ShellOOrganizationSlugProjectsProjectSlugSettingsGeneralRouteImport } from './routes/_shell/o/$organizationSlug/projects/$projectSlug/settings/general'
import { Route as ShellOOrganizationSlugProjectsProjectSlugActivityRunIdRouteImport } from './routes/_shell/o/$organizationSlug/projects/$projectSlug/activity/$runId'

const WebhookRoute = WebhookRouteImport.update({
  id: '/webhook',
  path: '/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const TestTriggerRoute = TestTriggerRouteImport.update({
  id: '/test/trigger',
  path: '/test/trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const TestStripeCheckoutRoute = TestStripeCheckoutRouteImport.update({
  id: '/test/stripe-checkout',
  path: '/test/stripe-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSmokeRoute = TestSmokeRouteImport.update({
  id: '/test/smoke',
  path: '/test/smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsSplatRoute = AssetsSplatRouteImport.update({
  id: '/assets/$',
  path: '/assets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRoute = ApiReferenceRouteImport.update({
  id: '/api/reference',
  path: '/api/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiDotjsonRoute = ApiOpenapiDotjsonRouteImport.update({
  id: '/api/openapi.json',
  path: '/api/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellOperatorRoute = ShellOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCliLoginRoute = ShellCliLoginRouteImport.update({
  id: '/cli-login',
  path: '/cli-login',
  getParentRoute: () => ShellRoute,
} as any)
const ApiV1CliAuthorizationsRoute = ApiV1CliAuthorizationsRouteImport.update({
  id: '/api/v1/cli-authorizations',
  path: '/api/v1/cli-authorizations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDaemonsEnrollRoute = ApiDaemonsEnrollRouteImport.update({
  id: '/api/daemons/enroll',
  path: '/api/daemons/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDaemonsDaemonIdRoute = ApiDaemonsDaemonIdRouteImport.update({
  id: '/api/daemons/$daemonId',
  path: '/api/daemons/$daemonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPlansRoute = ApiBillingPlansRouteImport.update({
  id: '/api/billing/plans',
  path: '/api/billing/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentExecutionsExecutionIdMcpRoute =
  AgentExecutionsExecutionIdMcpRouteImport.update({
    id: '/agent-executions/$executionId/mcp',
    path: '/agent-executions/$executionId/mcp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1CliAuthorizationsPollRoute =
  ApiV1CliAuthorizationsPollRouteImport.update({
    id: '/poll',
    path: '/poll',
    getParentRoute: () => ApiV1CliAuthorizationsRoute,
  } as any)
const ApiIntegrationsSlackEventsRoute =
  ApiIntegrationsSlackEventsRouteImport.update({
    id: '/api/integrations/slack/events',
    path: '/api/integrations/slack/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsSlackCallbackRoute =
  ApiIntegrationsSlackCallbackRouteImport.update({
    id: '/api/integrations/slack/callback',
    path: '/api/integrations/slack/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsLinearEventsRoute =
  ApiIntegrationsLinearEventsRouteImport.update({
    id: '/api/integrations/linear/events',
    path: '/api/integrations/linear/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsLinearCallbackRoute =
  ApiIntegrationsLinearCallbackRouteImport.update({
    id: '/api/integrations/linear/callback',
    path: '/api/integrations/linear/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGithubSetupRoute =
  ApiIntegrationsGithubSetupRouteImport.update({
    id: '/api/integrations/github/setup',
    path: '/api/integrations/github/setup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGithubCallbackRoute =
  ApiIntegrationsGithubCallbackRouteImport.update({
    id: '/api/integrations/github/callback',
    path: '/api/integrations/github/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsDiscordCallbackRoute =
  ApiIntegrationsDiscordCallbackRouteImport.update({
    id: '/api/integrations/discord/callback',
    path: '/api/integrations/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentExecutionsExecutionIdAttachmentsAttachmentIdRoute =
  AgentExecutionsExecutionIdAttachmentsAttachmentIdRouteImport.update({
    id: '/agent-executions/$executionId/attachments/$attachmentId',
    path: '/agent-executions/$executionId/attachments/$attachmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShellOOrganizationSlugUsageRoute =
  ShellOOrganizationSlugUsageRouteImport.update({
    id: '/o/$organizationSlug/usage',
    path: '/o/$organizationSlug/usage',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellOOrganizationSlugTeamRoute =
  ShellOOrganizationSlugTeamRouteImport.update({
    id: '/o/$organizationSlug/team',
    path: '/o/$organizationSlug/team',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellOOrganizationSlugProjectsRoute =
  ShellOOrganizationSlugProjectsRouteImport.update({
    id: '/o/$organizationSlug/projects',
    path: '/o/$organizationSlug/projects',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellOOrganizationSlugDaemonsRoute =
  ShellOOrganizationSlugDaemonsRouteImport.update({
    id: '/o/$organizationSlug/daemons',
    path: '/o/$organizationSlug/daemons',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellOOrganizationSlugConnectionsRoute =
  ShellOOrganizationSlugConnectionsRouteImport.update({
    id: '/o/$organizationSlug/connections',
    path: '/o/$organizationSlug/connections',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellOOrganizationSlugBillingRoute =
  ShellOOrganizationSlugBillingRouteImport.update({
    id: '/o/$organizationSlug/billing',
    path: '/o/$organizationSlug/billing',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellOOrganizationSlugApiKeysRoute =
  ShellOOrganizationSlugApiKeysRouteImport.update({
    id: '/o/$organizationSlug/api-keys',
    path: '/o/$organizationSlug/api-keys',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellOOrganizationSlugProjectsIndexRoute =
  ShellOOrganizationSlugProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShellOOrganizationSlugProjectsRoute,
  } as any)
const ShellOOrganizationSlugProjectsProjectSlugOverviewRoute =
  ShellOOrganizationSlugProjectsProjectSlugOverviewRouteImport.update({
    id: '/$projectSlug/overview',
    path: '/$projectSlug/overview',
    getParentRoute: () => ShellOOrganizationSlugProjectsRoute,
  } as any)
const ShellOOrganizationSlugProjectsProjectSlugConfigurationRoute =
  ShellOOrganizationSlugProjectsProjectSlugConfigurationRouteImport.update({
    id: '/$projectSlug/configuration',
    path: '/$projectSlug/configuration',
    getParentRoute: () => ShellOOrganizationSlugProjectsRoute,
  } as any)
const ShellOOrganizationSlugProjectsProjectSlugActivityRoute =
  ShellOOrganizationSlugProjectsProjectSlugActivityRouteImport.update({
    id: '/$projectSlug/activity',
    path: '/$projectSlug/activity',
    getParentRoute: () => ShellOOrganizationSlugProjectsRoute,
  } as any)
const ShellOOrganizationSlugProjectsProjectSlugActivityIndexRoute =
  ShellOOrganizationSlugProjectsProjectSlugActivityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      ShellOOrganizationSlugProjectsProjectSlugActivityRoute,
  } as any)
const ShellOOrganizationSlugProjectsProjectSlugSettingsGeneralRoute =
  ShellOOrganizationSlugProjectsProjectSlugSettingsGeneralRouteImport.update({
    id: '/$projectSlug/settings/general',
    path: '/$projectSlug/settings/general',
    getParentRoute: () => ShellOOrganizationSlugProjectsRoute,
  } as any)
const ShellOOrganizationSlugProjectsProjectSlugActivityRunIdRoute =
  ShellOOrganizationSlugProjectsProjectSlugActivityRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () =>
      ShellOOrganizationSlugProjectsProjectSlugActivityRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/health': typeof HealthRoute
  '/webhook': typeof WebhookRoute
  '/cli-login': typeof ShellCliLoginRoute
  '/operator': typeof ShellOperatorRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/reference': typeof ApiReferenceRoute
  '/assets/$': typeof AssetsSplatRoute
  '/test/smoke': typeof TestSmokeRoute
  '/test/stripe-checkout': typeof TestStripeCheckoutRoute
  '/test/trigger': typeof TestTriggerRoute
  '/agent-executions/$executionId/mcp': typeof AgentExecutionsExecutionIdMcpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/plans': typeof ApiBillingPlansRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/daemons/$daemonId': typeof ApiDaemonsDaemonIdRoute
  '/api/daemons/enroll': typeof ApiDaemonsEnrollRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/cli-authorizations': typeof ApiV1CliAuthorizationsRouteWithChildren
  '/o/$organizationSlug/api-keys': typeof ShellOOrganizationSlugApiKeysRoute
  '/o/$organizationSlug/billing': typeof ShellOOrganizationSlugBillingRoute
  '/o/$organizationSlug/connections': typeof ShellOOrganizationSlugConnectionsRoute
  '/o/$organizationSlug/daemons': typeof ShellOOrganizationSlugDaemonsRoute
  '/o/$organizationSlug/projects': typeof ShellOOrganizationSlugProjectsRouteWithChildren
  '/o/$organizationSlug/team': typeof ShellOOrganizationSlugTeamRoute
  '/o/$organizationSlug/usage': typeof ShellOOrganizationSlugUsageRoute
  '/agent-executions/$executionId/attachments/$attachmentId': typeof AgentExecutionsExecutionIdAttachmentsAttachmentIdRoute
  '/api/integrations/discord/callback': typeof ApiIntegrationsDiscordCallbackRoute
  '/api/integrations/github/callback': typeof ApiIntegrationsGithubCallbackRoute
  '/api/integrations/github/setup': typeof ApiIntegrationsGithubSetupRoute
  '/api/integrations/linear/callback': typeof ApiIntegrationsLinearCallbackRoute
  '/api/integrations/linear/events': typeof ApiIntegrationsLinearEventsRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/api/integrations/slack/events': typeof ApiIntegrationsSlackEventsRoute
  '/api/v1/cli-authorizations/poll': typeof ApiV1CliAuthorizationsPollRoute
  '/o/$organizationSlug/projects/': typeof ShellOOrganizationSlugProjectsIndexRoute
  '/o/$organizationSlug/projects/$projectSlug/activity': typeof ShellOOrganizationSlugProjectsProjectSlugActivityRouteWithChildren
  '/o/$organizationSlug/projects/$projectSlug/configuration': typeof ShellOOrganizationSlugProjectsProjectSlugConfigurationRoute
  '/o/$organizationSlug/projects/$projectSlug/overview': typeof ShellOOrganizationSlugProjectsProjectSlugOverviewRoute
  '/o/$organizationSlug/projects/$projectSlug/activity/$runId': typeof ShellOOrganizationSlugProjectsProjectSlugActivityRunIdRoute
  '/o/$organizationSlug/projects/$projectSlug/settings/general': typeof ShellOOrganizationSlugProjectsProjectSlugSettingsGeneralRoute
  '/o/$organizationSlug/projects/$projectSlug/activity/': typeof ShellOOrganizationSlugProjectsProjectSlugActivityIndexRoute
}
export interface FileRoutesByTo {
  '/health': typeof HealthRoute
  '/webhook': typeof WebhookRoute
  '/cli-login': typeof ShellCliLoginRoute
  '/operator': typeof ShellOperatorRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/reference': typeof ApiReferenceRoute
  '/assets/$': typeof AssetsSplatRoute
  '/test/smoke': typeof TestSmokeRoute
  '/test/stripe-checkout': typeof TestStripeCheckoutRoute
  '/test/trigger': typeof TestTriggerRoute
  '/': typeof ShellIndexRoute
  '/agent-executions/$executionId/mcp': typeof AgentExecutionsExecutionIdMcpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/plans': typeof ApiBillingPlansRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/daemons/$daemonId': typeof ApiDaemonsDaemonIdRoute
  '/api/daemons/enroll': typeof ApiDaemonsEnrollRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/cli-authorizations': typeof ApiV1CliAuthorizationsRouteWithChildren
  '/o/$organizationSlug/api-keys': typeof ShellOOrganizationSlugApiKeysRoute
  '/o/$organizationSlug/billing': typeof ShellOOrganizationSlugBillingRoute
  '/o/$organizationSlug/connections': typeof ShellOOrganizationSlugConnectionsRoute
  '/o/$organizationSlug/daemons': typeof ShellOOrganizationSlugDaemonsRoute
  '/o/$organizationSlug/team': typeof ShellOOrganizationSlugTeamRoute
  '/o/$organizationSlug/usage': typeof ShellOOrganizationSlugUsageRoute
  '/agent-executions/$executionId/attachments/$attachmentId': typeof AgentExecutionsExecutionIdAttachmentsAttachmentIdRoute
  '/api/integrations/discord/callback': typeof ApiIntegrationsDiscordCallbackRoute
  '/api/integrations/github/callback': typeof ApiIntegrationsGithubCallbackRoute
  '/api/integrations/github/setup': typeof ApiIntegrationsGithubSetupRoute
  '/api/integrations/linear/callback': typeof ApiIntegrationsLinearCallbackRoute
  '/api/integrations/linear/events': typeof ApiIntegrationsLinearEventsRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/api/integrations/slack/events': typeof ApiIntegrationsSlackEventsRoute
  '/api/v1/cli-authorizations/poll': typeof ApiV1CliAuthorizationsPollRoute
  '/o/$organizationSlug/projects': typeof ShellOOrganizationSlugProjectsIndexRoute
  '/o/$organizationSlug/projects/$projectSlug/configuration': typeof ShellOOrganizationSlugProjectsProjectSlugConfigurationRoute
  '/o/$organizationSlug/projects/$projectSlug/overview': typeof ShellOOrganizationSlugProjectsProjectSlugOverviewRoute
  '/o/$organizationSlug/projects/$projectSlug/activity/$runId': typeof ShellOOrganizationSlugProjectsProjectSlugActivityRunIdRoute
  '/o/$organizationSlug/projects/$projectSlug/settings/general': typeof ShellOOrganizationSlugProjectsProjectSlugSettingsGeneralRoute
  '/o/$organizationSlug/projects/$projectSlug/activity': typeof ShellOOrganizationSlugProjectsProjectSlugActivityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/health': typeof HealthRoute
  '/webhook': typeof WebhookRoute
  '/_shell/cli-login': typeof ShellCliLoginRoute
  '/_shell/operator': typeof ShellOperatorRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/reference': typeof ApiReferenceRoute
  '/assets/$': typeof AssetsSplatRoute
  '/test/smoke': typeof TestSmokeRoute
  '/test/stripe-checkout': typeof TestStripeCheckoutRoute
  '/test/trigger': typeof TestTriggerRoute
  '/_shell/': typeof ShellIndexRoute
  '/agent-executions/$executionId/mcp': typeof AgentExecutionsExecutionIdMcpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/plans': typeof ApiBillingPlansRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/daemons/$daemonId': typeof ApiDaemonsDaemonIdRoute
  '/api/daemons/enroll': typeof ApiDaemonsEnrollRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/cli-authorizations': typeof ApiV1CliAuthorizationsRouteWithChildren
  '/_shell/o/$organizationSlug/api-keys': typeof ShellOOrganizationSlugApiKeysRoute
  '/_shell/o/$organizationSlug/billing': typeof ShellOOrganizationSlugBillingRoute
  '/_shell/o/$organizationSlug/connections': typeof ShellOOrganizationSlugConnectionsRoute
  '/_shell/o/$organizationSlug/daemons': typeof ShellOOrganizationSlugDaemonsRoute
  '/_shell/o/$organizationSlug/projects': typeof ShellOOrganizationSlugProjectsRouteWithChildren
  '/_shell/o/$organizationSlug/team': typeof ShellOOrganizationSlugTeamRoute
  '/_shell/o/$organizationSlug/usage': typeof ShellOOrganizationSlugUsageRoute
  '/agent-executions/$executionId/attachments/$attachmentId': typeof AgentExecutionsExecutionIdAttachmentsAttachmentIdRoute
  '/api/integrations/discord/callback': typeof ApiIntegrationsDiscordCallbackRoute
  '/api/integrations/github/callback': typeof ApiIntegrationsGithubCallbackRoute
  '/api/integrations/github/setup': typeof ApiIntegrationsGithubSetupRoute
  '/api/integrations/linear/callback': typeof ApiIntegrationsLinearCallbackRoute
  '/api/integrations/linear/events': typeof ApiIntegrationsLinearEventsRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/api/integrations/slack/events': typeof ApiIntegrationsSlackEventsRoute
  '/api/v1/cli-authorizations/poll': typeof ApiV1CliAuthorizationsPollRoute
  '/_shell/o/$organizationSlug/projects/': typeof ShellOOrganizationSlugProjectsIndexRoute
  '/_shell/o/$organizationSlug/projects/$projectSlug/activity': typeof ShellOOrganizationSlugProjectsProjectSlugActivityRouteWithChildren
  '/_shell/o/$organizationSlug/projects/$projectSlug/configuration': typeof ShellOOrganizationSlugProjectsProjectSlugConfigurationRoute
  '/_shell/o/$organizationSlug/projects/$projectSlug/overview': typeof ShellOOrganizationSlugProjectsProjectSlugOverviewRoute
  '/_shell/o/$organizationSlug/projects/$projectSlug/activity/$runId': typeof ShellOOrganizationSlugProjectsProjectSlugActivityRunIdRoute
  '/_shell/o/$organizationSlug/projects/$projectSlug/settings/general': typeof ShellOOrganizationSlugProjectsProjectSlugSettingsGeneralRoute
  '/_shell/o/$organizationSlug/projects/$projectSlug/activity/': typeof ShellOOrganizationSlugProjectsProjectSlugActivityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/webhook'
    | '/cli-login'
    | '/operator'
    | '/api/openapi.json'
    | '/api/reference'
    | '/assets/$'
    | '/test/smoke'
    | '/test/stripe-checkout'
    | '/test/trigger'
    | '/agent-executions/$executionId/mcp'
    | '/api/auth/$'
    | '/api/billing/plans'
    | '/api/billing/webhook'
    | '/api/daemons/$daemonId'
    | '/api/daemons/enroll'
    | '/api/v1/$'
    | '/api/v1/cli-authorizations'
    | '/o/$organizationSlug/api-keys'
    | '/o/$organizationSlug/billing'
    | '/o/$organizationSlug/connections'
    | '/o/$organizationSlug/daemons'
    | '/o/$organizationSlug/projects'
    | '/o/$organizationSlug/team'
    | '/o/$organizationSlug/usage'
    | '/agent-executions/$executionId/attachments/$attachmentId'
    | '/api/integrations/discord/callback'
    | '/api/integrations/github/callback'
    | '/api/integrations/github/setup'
    | '/api/integrations/linear/callback'
    | '/api/integrations/linear/events'
    | '/api/integrations/slack/callback'
    | '/api/integrations/slack/events'
    | '/api/v1/cli-authorizations/poll'
    | '/o/$organizationSlug/projects/'
    | '/o/$organizationSlug/projects/$projectSlug/activity'
    | '/o/$organizationSlug/projects/$projectSlug/configuration'
    | '/o/$organizationSlug/projects/$projectSlug/overview'
    | '/o/$organizationSlug/projects/$projectSlug/activity/$runId'
    | '/o/$organizationSlug/projects/$projectSlug/settings/general'
    | '/o/$organizationSlug/projects/$projectSlug/activity/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/health'
    | '/webhook'
    | '/cli-login'
    | '/operator'
    | '/api/openapi.json'
    | '/api/reference'
    | '/assets/$'
    | '/test/smoke'
    | '/test/stripe-checkout'
    | '/test/trigger'
    | '/'
    | '/agent-executions/$executionId/mcp'
    | '/api/auth/$'
    | '/api/billing/plans'
    | '/api/billing/webhook'
    | '/api/daemons/$daemonId'
    | '/api/daemons/enroll'
    | '/api/v1/$'
    | '/api/v1/cli-authorizations'
    | '/o/$organizationSlug/api-keys'
    | '/o/$organizationSlug/billing'
    | '/o/$organizationSlug/connections'
    | '/o/$organizationSlug/daemons'
    | '/o/$organizationSlug/team'
    | '/o/$organizationSlug/usage'
    | '/agent-executions/$executionId/attachments/$attachmentId'
    | '/api/integrations/discord/callback'
    | '/api/integrations/github/callback'
    | '/api/integrations/github/setup'
    | '/api/integrations/linear/callback'
    | '/api/integrations/linear/events'
    | '/api/integrations/slack/callback'
    | '/api/integrations/slack/events'
    | '/api/v1/cli-authorizations/poll'
    | '/o/$organizationSlug/projects'
    | '/o/$organizationSlug/projects/$projectSlug/configuration'
    | '/o/$organizationSlug/projects/$projectSlug/overview'
    | '/o/$organizationSlug/projects/$projectSlug/activity/$runId'
    | '/o/$organizationSlug/projects/$projectSlug/settings/general'
    | '/o/$organizationSlug/projects/$projectSlug/activity'
  id:
    | '__root__'
    | '/_shell'
    | '/health'
    | '/webhook'
    | '/_shell/cli-login'
    | '/_shell/operator'
    | '/api/openapi.json'
    | '/api/reference'
    | '/assets/$'
    | '/test/smoke'
    | '/test/stripe-checkout'
    | '/test/trigger'
    | '/_shell/'
    | '/agent-executions/$executionId/mcp'
    | '/api/auth/$'
    | '/api/billing/plans'
    | '/api/billing/webhook'
    | '/api/daemons/$daemonId'
    | '/api/daemons/enroll'
    | '/api/v1/$'
    | '/api/v1/cli-authorizations'
    | '/_shell/o/$organizationSlug/api-keys'
    | '/_shell/o/$organizationSlug/billing'
    | '/_shell/o/$organizationSlug/connections'
    | '/_shell/o/$organizationSlug/daemons'
    | '/_shell/o/$organizationSlug/projects'
    | '/_shell/o/$organizationSlug/team'
    | '/_shell/o/$organizationSlug/usage'
    | '/agent-executions/$executionId/attachments/$attachmentId'
    | '/api/integrations/discord/callback'
    | '/api/integrations/github/callback'
    | '/api/integrations/github/setup'
    | '/api/integrations/linear/callback'
    | '/api/integrations/linear/events'
    | '/api/integrations/slack/callback'
    | '/api/integrations/slack/events'
    | '/api/v1/cli-authorizations/poll'
    | '/_shell/o/$organizationSlug/projects/'
    | '/_shell/o/$organizationSlug/projects/$projectSlug/activity'
    | '/_shell/o/$organizationSlug/projects/$projectSlug/configuration'
    | '/_shell/o/$organizationSlug/projects/$projectSlug/overview'
    | '/_shell/o/$organizationSlug/projects/$projectSlug/activity/$runId'
    | '/_shell/o/$organizationSlug/projects/$projectSlug/settings/general'
    | '/_shell/o/$organizationSlug/projects/$projectSlug/activity/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  HealthRoute: typeof HealthRoute
  WebhookRoute: typeof WebhookRoute
  ApiOpenapiDotjsonRoute: typeof ApiOpenapiDotjsonRoute
  ApiReferenceRoute: typeof ApiReferenceRoute
  AssetsSplatRoute: typeof AssetsSplatRoute
  TestSmokeRoute: typeof TestSmokeRoute
  TestStripeCheckoutRoute: typeof TestStripeCheckoutRoute
  TestTriggerRoute: typeof TestTriggerRoute
  AgentExecutionsExecutionIdMcpRoute: typeof AgentExecutionsExecutionIdMcpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBillingPlansRoute: typeof ApiBillingPlansRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiDaemonsDaemonIdRoute: typeof ApiDaemonsDaemonIdRoute
  ApiDaemonsEnrollRoute: typeof ApiDaemonsEnrollRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiV1CliAuthorizationsRoute: typeof ApiV1CliAuthorizationsRouteWithChildren
  AgentExecutionsExecutionIdAttachmentsAttachmentIdRoute: typeof AgentExecutionsExecutionIdAttachmentsAttachmentIdRoute
  ApiIntegrationsDiscordCallbackRoute: typeof ApiIntegrationsDiscordCallbackRoute
  ApiIntegrationsGithubCallbackRoute: typeof ApiIntegrationsGithubCallbackRoute
  ApiIntegrationsGithubSetupRoute: typeof ApiIntegrationsGithubSetupRoute
  ApiIntegrationsLinearCallbackRoute: typeof ApiIntegrationsLinearCallbackRoute
  ApiIntegrationsLinearEventsRoute: typeof ApiIntegrationsLinearEventsRoute
  ApiIntegrationsSlackCallbackRoute: typeof ApiIntegrationsSlackCallbackRoute
  ApiIntegrationsSlackEventsRoute: typeof ApiIntegrationsSlackEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhook': {
      id: '/webhook'
      path: '/webhook'
      fullPath: '/webhook'
      preLoaderRoute: typeof WebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/test/trigger': {
      id: '/test/trigger'
      path: '/test/trigger'
      fullPath: '/test/trigger'
      preLoaderRoute: typeof TestTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/stripe-checkout': {
      id: '/test/stripe-checkout'
      path: '/test/stripe-checkout'
      fullPath: '/test/stripe-checkout'
      preLoaderRoute: typeof TestStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/smoke': {
      id: '/test/smoke'
      path: '/test/smoke'
      fullPath: '/test/smoke'
      preLoaderRoute: typeof TestSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$': {
      id: '/assets/$'
      path: '/assets/$'
      fullPath: '/assets/$'
      preLoaderRoute: typeof AssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reference': {
      id: '/api/reference'
      path: '/api/reference'
      fullPath: '/api/reference'
      preLoaderRoute: typeof ApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/api/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/operator': {
      id: '/_shell/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof ShellOperatorRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/cli-login': {
      id: '/_shell/cli-login'
      path: '/cli-login'
      fullPath: '/cli-login'
      preLoaderRoute: typeof ShellCliLoginRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/v1/cli-authorizations': {
      id: '/api/v1/cli-authorizations'
      path: '/api/v1/cli-authorizations'
      fullPath: '/api/v1/cli-authorizations'
      preLoaderRoute: typeof ApiV1CliAuthorizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daemons/enroll': {
      id: '/api/daemons/enroll'
      path: '/api/daemons/enroll'
      fullPath: '/api/daemons/enroll'
      preLoaderRoute: typeof ApiDaemonsEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daemons/$daemonId': {
      id: '/api/daemons/$daemonId'
      path: '/api/daemons/$daemonId'
      fullPath: '/api/daemons/$daemonId'
      preLoaderRoute: typeof ApiDaemonsDaemonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/plans': {
      id: '/api/billing/plans'
      path: '/api/billing/plans'
      fullPath: '/api/billing/plans'
      preLoaderRoute: typeof ApiBillingPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-executions/$executionId/mcp': {
      id: '/agent-executions/$executionId/mcp'
      path: '/agent-executions/$executionId/mcp'
      fullPath: '/agent-executions/$executionId/mcp'
      preLoaderRoute: typeof AgentExecutionsExecutionIdMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/cli-authorizations/poll': {
      id: '/api/v1/cli-authorizations/poll'
      path: '/poll'
      fullPath: '/api/v1/cli-authorizations/poll'
      preLoaderRoute: typeof ApiV1CliAuthorizationsPollRouteImport
      parentRoute: typeof ApiV1CliAuthorizationsRoute
    }
    '/api/integrations/slack/events': {
      id: '/api/integrations/slack/events'
      path: '/api/integrations/slack/events'
      fullPath: '/api/integrations/slack/events'
      preLoaderRoute: typeof ApiIntegrationsSlackEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/slack/callback': {
      id: '/api/integrations/slack/callback'
      path: '/api/integrations/slack/callback'
      fullPath: '/api/integrations/slack/callback'
      preLoaderRoute: typeof ApiIntegrationsSlackCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/linear/events': {
      id: '/api/integrations/linear/events'
      path: '/api/integrations/linear/events'
      fullPath: '/api/integrations/linear/events'
      preLoaderRoute: typeof ApiIntegrationsLinearEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/linear/callback': {
      id: '/api/integrations/linear/callback'
      path: '/api/integrations/linear/callback'
      fullPath: '/api/integrations/linear/callback'
      preLoaderRoute: typeof ApiIntegrationsLinearCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/github/setup': {
      id: '/api/integrations/github/setup'
      path: '/api/integrations/github/setup'
      fullPath: '/api/integrations/github/setup'
      preLoaderRoute: typeof ApiIntegrationsGithubSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/github/callback': {
      id: '/api/integrations/github/callback'
      path: '/api/integrations/github/callback'
      fullPath: '/api/integrations/github/callback'
      preLoaderRoute: typeof ApiIntegrationsGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/discord/callback': {
      id: '/api/integrations/discord/callback'
      path: '/api/integrations/discord/callback'
      fullPath: '/api/integrations/discord/callback'
      preLoaderRoute: typeof ApiIntegrationsDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-executions/$executionId/attachments/$attachmentId': {
      id: '/agent-executions/$executionId/attachments/$attachmentId'
      path: '/agent-executions/$executionId/attachments/$attachmentId'
      fullPath: '/agent-executions/$executionId/attachments/$attachmentId'
      preLoaderRoute: typeof AgentExecutionsExecutionIdAttachmentsAttachmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/o/$organizationSlug/usage': {
      id: '/_shell/o/$organizationSlug/usage'
      path: '/o/$organizationSlug/usage'
      fullPath: '/o/$organizationSlug/usage'
      preLoaderRoute: typeof ShellOOrganizationSlugUsageRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/o/$organizationSlug/team': {
      id: '/_shell/o/$organizationSlug/team'
      path: '/o/$organizationSlug/team'
      fullPath: '/o/$organizationSlug/team'
      preLoaderRoute: typeof ShellOOrganizationSlugTeamRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/o/$organizationSlug/projects': {
      id: '/_shell/o/$organizationSlug/projects'
      path: '/o/$organizationSlug/projects'
      fullPath: '/o/$organizationSlug/projects'
      preLoaderRoute: typeof ShellOOrganizationSlugProjectsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/o/$organizationSlug/daemons': {
      id: '/_shell/o/$organizationSlug/daemons'
      path: '/o/$organizationSlug/daemons'
      fullPath: '/o/$organizationSlug/daemons'
      preLoaderRoute: typeof ShellOOrganizationSlugDaemonsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/o/$organizationSlug/connections': {
      id: '/_shell/o/$organizationSlug/connections'
      path: '/o/$organizationSlug/connections'
      fullPath: '/o/$organizationSlug/connections'
      preLoaderRoute: typeof ShellOOrganizationSlugConnectionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/o/$organizationSlug/billing': {
      id: '/_shell/o/$organizationSlug/billing'
      path: '/o/$organizationSlug/billing'
      fullPath: '/o/$organizationSlug/billing'
      preLoaderRoute: typeof ShellOOrganizationSlugBillingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/o/$organizationSlug/api-keys': {
      id: '/_shell/o/$organizationSlug/api-keys'
      path: '/o/$organizationSlug/api-keys'
      fullPath: '/o/$organizationSlug/api-keys'
      preLoaderRoute: typeof ShellOOrganizationSlugApiKeysRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/o/$organizationSlug/projects/': {
      id: '/_shell/o/$organizationSlug/projects/'
      path: '/'
      fullPath: '/o/$organizationSlug/projects/'
      preLoaderRoute: typeof ShellOOrganizationSlugProjectsIndexRouteImport
      parentRoute: typeof ShellOOrganizationSlugProjectsRoute
    }
    '/_shell/o/$organizationSlug/projects/$projectSlug/overview': {
      id: '/_shell/o/$organizationSlug/projects/$projectSlug/overview'
      path: '/$projectSlug/overview'
      fullPath: '/o/$organizationSlug/projects/$projectSlug/overview'
      preLoaderRoute: typeof ShellOOrganizationSlugProjectsProjectSlugOverviewRouteImport
      parentRoute: typeof ShellOOrganizationSlugProjectsRoute
    }
    '/_shell/o/$organizationSlug/projects/$projectSlug/configuration': {
      id: '/_shell/o/$organizationSlug/projects/$projectSlug/configuration'
      path: '/$projectSlug/configuration'
      fullPath: '/o/$organizationSlug/projects/$projectSlug/configuration'
      preLoaderRoute: typeof ShellOOrganizationSlugProjectsProjectSlugConfigurationRouteImport
      parentRoute: typeof ShellOOrganizationSlugProjectsRoute
    }
    '/_shell/o/$organizationSlug/projects/$projectSlug/activity': {
      id: '/_shell/o/$organizationSlug/projects/$projectSlug/activity'
      path: '/$projectSlug/activity'
      fullPath: '/o/$organizationSlug/projects/$projectSlug/activity'
      preLoaderRoute: typeof ShellOOrganizationSlugProjectsProjectSlugActivityRouteImport
      parentRoute: typeof ShellOOrganizationSlugProjectsRoute
    }
    '/_shell/o/$organizationSlug/projects/$projectSlug/activity/': {
      id: '/_shell/o/$organizationSlug/projects/$projectSlug/activity/'
      path: '/'
      fullPath: '/o/$organizationSlug/projects/$projectSlug/activity/'
      preLoaderRoute: typeof ShellOOrganizationSlugProjectsProjectSlugActivityIndexRouteImport
      parentRoute: typeof ShellOOrganizationSlugProjectsProjectSlugActivityRoute
    }
    '/_shell/o/$organizationSlug/projects/$projectSlug/settings/general': {
      id: '/_shell/o/$organizationSlug/projects/$projectSlug/settings/general'
      path: '/$projectSlug/settings/general'
      fullPath: '/o/$organizationSlug/projects/$projectSlug/settings/general'
      preLoaderRoute: typeof ShellOOrganizationSlugProjectsProjectSlugSettingsGeneralRouteImport
      parentRoute: typeof ShellOOrganizationSlugProjectsRoute
    }
    '/_shell/o/$organizationSlug/projects/$projectSlug/activity/$runId': {
      id: '/_shell/o/$organizationSlug/projects/$projectSlug/activity/$runId'
      path: '/$runId'
      fullPath: '/o/$organizationSlug/projects/$projectSlug/activity/$runId'
      preLoaderRoute: typeof ShellOOrganizationSlugProjectsProjectSlugActivityRunIdRouteImport
      parentRoute: typeof ShellOOrganizationSlugProjectsProjectSlugActivityRoute
    }
  }
}

interface ShellOOrganizationSlugProjectsProjectSlugActivityRouteChildren {
  ShellOOrganizationSlugProjectsProjectSlugActivityRunIdRoute: typeof ShellOOrganizationSlugProjectsProjectSlugActivityRunIdRoute
  ShellOOrganizationSlugProjectsProjectSlugActivityIndexRoute: typeof ShellOOrganizationSlugProjectsProjectSlugActivityIndexRoute
}

const ShellOOrganizationSlugProjectsProjectSlugActivityRouteChildren: ShellOOrganizationSlugProjectsProjectSlugActivityRouteChildren =
  {
    ShellOOrganizationSlugProjectsProjectSlugActivityRunIdRoute:
      ShellOOrganizationSlugProjectsProjectSlugActivityRunIdRoute,
    ShellOOrganizationSlugProjectsProjectSlugActivityIndexRoute:
      ShellOOrganizationSlugProjectsProjectSlugActivityIndexRoute,
  }

const ShellOOrganizationSlugProjectsProjectSlugActivityRouteWithChildren =
  ShellOOrganizationSlugProjectsProjectSlugActivityRoute._addFileChildren(
    ShellOOrganizationSlugProjectsProjectSlugActivityRouteChildren,
  )

interface ShellOOrganizationSlugProjectsRouteChildren {
  ShellOOrganizationSlugProjectsIndexRoute: typeof ShellOOrganizationSlugProjectsIndexRoute
  ShellOOrganizationSlugProjectsProjectSlugActivityRoute: typeof ShellOOrganizationSlugProjectsProjectSlugActivityRouteWithChildren
  ShellOOrganizationSlugProjectsProjectSlugConfigurationRoute: typeof ShellOOrganizationSlugProjectsProjectSlugConfigurationRoute
  ShellOOrganizationSlugProjectsProjectSlugOverviewRoute: typeof ShellOOrganizationSlugProjectsProjectSlugOverviewRoute
  ShellOOrganizationSlugProjectsProjectSlugSettingsGeneralRoute: typeof ShellOOrganizationSlugProjectsProjectSlugSettingsGeneralRoute
}

const ShellOOrganizationSlugProjectsRouteChildren: ShellOOrganizationSlugProjectsRouteChildren =
  {
    ShellOOrganizationSlugProjectsIndexRoute:
      ShellOOrganizationSlugProjectsIndexRoute,
    ShellOOrganizationSlugProjectsProjectSlugActivityRoute:
      ShellOOrganizationSlugProjectsProjectSlugActivityRouteWithChildren,
    ShellOOrganizationSlugProjectsProjectSlugConfigurationRoute:
      ShellOOrganizationSlugProjectsProjectSlugConfigurationRoute,
    ShellOOrganizationSlugProjectsProjectSlugOverviewRoute:
      ShellOOrganizationSlugProjectsProjectSlugOverviewRoute,
    ShellOOrganizationSlugProjectsProjectSlugSettingsGeneralRoute:
      ShellOOrganizationSlugProjectsProjectSlugSettingsGeneralRoute,
  }

const ShellOOrganizationSlugProjectsRouteWithChildren =
  ShellOOrganizationSlugProjectsRoute._addFileChildren(
    ShellOOrganizationSlugProjectsRouteChildren,
  )

interface ShellRouteChildren {
  ShellCliLoginRoute: typeof ShellCliLoginRoute
  ShellOperatorRoute: typeof ShellOperatorRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellOOrganizationSlugApiKeysRoute: typeof ShellOOrganizationSlugApiKeysRoute
  ShellOOrganizationSlugBillingRoute: typeof ShellOOrganizationSlugBillingRoute
  ShellOOrganizationSlugConnectionsRoute: typeof ShellOOrganizationSlugConnectionsRoute
  ShellOOrganizationSlugDaemonsRoute: typeof ShellOOrganizationSlugDaemonsRoute
  ShellOOrganizationSlugProjectsRoute: typeof ShellOOrganizationSlugProjectsRouteWithChildren
  ShellOOrganizationSlugTeamRoute: typeof ShellOOrganizationSlugTeamRoute
  ShellOOrganizationSlugUsageRoute: typeof ShellOOrganizationSlugUsageRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellCliLoginRoute: ShellCliLoginRoute,
  ShellOperatorRoute: ShellOperatorRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellOOrganizationSlugApiKeysRoute: ShellOOrganizationSlugApiKeysRoute,
  ShellOOrganizationSlugBillingRoute: ShellOOrganizationSlugBillingRoute,
  ShellOOrganizationSlugConnectionsRoute:
    ShellOOrganizationSlugConnectionsRoute,
  ShellOOrganizationSlugDaemonsRoute: ShellOOrganizationSlugDaemonsRoute,
  ShellOOrganizationSlugProjectsRoute:
    ShellOOrganizationSlugProjectsRouteWithChildren,
  ShellOOrganizationSlugTeamRoute: ShellOOrganizationSlugTeamRoute,
  ShellOOrganizationSlugUsageRoute: ShellOOrganizationSlugUsageRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface ApiV1CliAuthorizationsRouteChildren {
  ApiV1CliAuthorizationsPollRoute: typeof ApiV1CliAuthorizationsPollRoute
}

const ApiV1CliAuthorizationsRouteChildren: ApiV1CliAuthorizationsRouteChildren =
  {
    ApiV1CliAuthorizationsPollRoute: ApiV1CliAuthorizationsPollRoute,
  }

const ApiV1CliAuthorizationsRouteWithChildren =
  ApiV1CliAuthorizationsRoute._addFileChildren(
    ApiV1CliAuthorizationsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  HealthRoute: HealthRoute,
  WebhookRoute: WebhookRoute,
  ApiOpenapiDotjsonRoute: ApiOpenapiDotjsonRoute,
  ApiReferenceRoute: ApiReferenceRoute,
  AssetsSplatRoute: AssetsSplatRoute,
  TestSmokeRoute: TestSmokeRoute,
  TestStripeCheckoutRoute: TestStripeCheckoutRoute,
  TestTriggerRoute: TestTriggerRoute,
  AgentExecutionsExecutionIdMcpRoute: AgentExecutionsExecutionIdMcpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBillingPlansRoute: ApiBillingPlansRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiDaemonsDaemonIdRoute: ApiDaemonsDaemonIdRoute,
  ApiDaemonsEnrollRoute: ApiDaemonsEnrollRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiV1CliAuthorizationsRoute: ApiV1CliAuthorizationsRouteWithChildren,
  AgentExecutionsExecutionIdAttachmentsAttachmentIdRoute:
    AgentExecutionsExecutionIdAttachmentsAttachmentIdRoute,
  ApiIntegrationsDiscordCallbackRoute: ApiIntegrationsDiscordCallbackRoute,
  ApiIntegrationsGithubCallbackRoute: ApiIntegrationsGithubCallbackRoute,
  ApiIntegrationsGithubSetupRoute: ApiIntegrationsGithubSetupRoute,
  ApiIntegrationsLinearCallbackRoute: ApiIntegrationsLinearCallbackRoute,
  ApiIntegrationsLinearEventsRoute: ApiIntegrationsLinearEventsRoute,
  ApiIntegrationsSlackCallbackRoute: ApiIntegrationsSlackCallbackRoute,
  ApiIntegrationsSlackEventsRoute: ApiIntegrationsSlackEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
